// backend/routes/counsellorRequests.js
const express = require("express");
const router = express.Router();
const db = require("../db");
const bcrypt = require("bcryptjs");
const sendAdminNotification = require("../utilityAdmin/notificationHelper");

// ============================================
// COUNSELLOR APPLICATION
// ============================================

// Submit counsellor application (no token required - public)
router.post("/apply", async (req, res) => {
  console.log("========================================");
  console.log("COUNSELLOR APPLICATION RECEIVED");
  console.log("Request body:", req.body);
  console.log("========================================");
  
  try {
    const { 
      name, nickname, email, dob, gender,
      university_id, student_id,
      emergency_contact_name, emergency_contact_phone, emergency_contact_relationship,
      qualification, experience 
    } = req.body;

    // ✅ Password is no longer required for counsellor applications
    if (!name || !email || !university_id || !dob || !gender) {
      console.log("Missing required fields");
      return res.status(400).json({ 
        msg: "Please fill in all required fields"
      });
    }

    // Check if email already exists in users table
    const [existingUser] = await db.promise().query(
      "SELECT id FROM users WHERE email = ?",
      [email]
    );

    if (existingUser.length > 0) {
      console.log("Email already registered:", email);
      return res.status(400).json({ msg: "This email is already registered. Please login or use a different email." });
    }

    // Check if there's already a pending or approved request
    const [existingRequest] = await db.promise().query(
      "SELECT id, status FROM counsellor_requests WHERE email = ? AND status != 'rejected'",
      [email]
    );

    if (existingRequest.length > 0) {
      if (existingRequest[0].status === 'pending') {
        return res.status(400).json({ msg: "You already have a pending application. Please wait for admin review." });
      }
      if (existingRequest[0].status === 'approved') {
        return res.status(400).json({ msg: "Your counsellor account has already been approved. Please login." });
      }
    }

    // ✅ No password hashing needed - will be set when approved
    // Default password will be generated by admin on approval

    console.log("Inserting into counsellor_requests...");
    const insertResult = await db.promise().query(
      `INSERT INTO counsellor_requests 
       (name, nickname, email, password, dob, gender,
        university_id, student_id,
        emergency_contact_name, emergency_contact_phone, emergency_contact_relationship,
        qualification, experience, status) 
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending')`,
      [
        name, 
        nickname || null, 
        email, 
        null, // ✅ No password stored
        dob, 
        gender,
        university_id, 
        student_id || null,
        emergency_contact_name || null, 
        emergency_contact_phone || null, 
        emergency_contact_relationship || null,
        qualification || null, 
        experience || null
      ]
    );

    console.log("Counsellor application submitted. ID:", insertResult[0].insertId);
    console.log("Email:", email);

    // Send admin notification
    await sendAdminNotification(
      'counsellor_request',
      'New Counsellor Request',
      `${name} applied to become a counsellor`,
      '/admin/counsellor-requests',
      insertResult[0].insertId
    );

    res.json({ 
      msg: "Your counsellor registration request has been submitted. Please wait for admin approval.",
    });

  } catch (error) {
    console.error("========================================");
    console.error("COUNSELLOR APPLICATION ERROR:");
    console.error("Error message:", error.message);
    console.error("Error code:", error.code);
    console.error("========================================");
    
    if (error.code === 'ER_DUP_ENTRY') {
      return res.status(400).json({ msg: "An application with this email already exists." });
    }
    
    res.status(500).json({ 
      msg: "Failed to submit application", 
      error: error.message,
      code: error.code 
    });
  }
});

// Check if email exists
router.post("/check-email", async (req, res) => {
  const { email } = req.body;

  console.log("Checking email:", email);

  try {
    // Check in users table
    const [users] = await db.promise().query(
      "SELECT id FROM users WHERE email = ?",
      [email]
    );
    
    // Check in counsellor_requests table
    const [requests] = await db.promise().query(
      "SELECT id, status FROM counsellor_requests WHERE email = ? AND status = 'pending'",
      [email]
    );

    res.json({ 
      exists: users.length > 0,
      hasPendingRequest: requests.length > 0 
    });
  } catch (error) {
    console.error("Check email error:", error);
    res.status(500).json({ msg: "Failed to check email" });
  }
});

// Get request status
router.get("/status/:email", async (req, res) => {
  const { email } = req.params;

  console.log("Getting status for:", email);

  try {
    const [results] = await db.promise().query(
      `SELECT id, status, created_at, admin_notes 
       FROM counsellor_requests 
       WHERE email = ? 
       ORDER BY created_at DESC LIMIT 1`,
      [email]
    );
    
    res.json(results[0] || null);
  } catch (error) {
    console.error("Fetch request status error:", error);
    res.status(500).json({ msg: "Failed to fetch status" });
  }
});

module.exports = router;