// backend/routes/studentExport.js
const express = require("express");
const router = express.Router();
const db = require("../db");
const verifyToken = require("../middleware/authmiddleware");
const PDFDocument = require('pdfkit');
const { Parser } = require('json2csv');

/* =========================================================================
 * PDF DESIGN SYSTEM
 * Shared tokens + drawing helpers for the journal and assessment PDF exports
 * below, matching the visual language already used in the Lumora wellness
 * report (same palette, section headings, cards, and footer treatment) so
 * every PDF a student or counsellor downloads feels consistent. Purely
 * presentational — does not touch routes, queries, auth checks, response
 * headers, filenames, or the CSV export endpoints further down this file.
 * ========================================================================= */

const PDF_COLORS = {
  primary:      '#4F46E5',
  primaryLight: '#EEF2FF',
  danger:       '#DC2626',
  dangerLight:  '#FEF2F2',
  warning:      '#D97706',
  warningLight: '#FFFBEB',
  success:      '#16A34A',
  successLight: '#F0FDF4',
  text:         '#111827',
  textMuted:    '#6B7280',
  textLight:    '#9CA3AF',
  border:       '#E5E7EB',
  bg:           '#F9FAFB',
  white:        '#FFFFFF',
};

const PDF_PAGE_W = 595.28;          // A4 width in points
const PDF_PAGE_H = 841.89;          // A4 height in points
const PDF_MARGIN = 50;
const PDF_CONTENT_W = PDF_PAGE_W - PDF_MARGIN * 2;
const PDF_MAX_Y = PDF_PAGE_H - 50;  // leave room for the footer

function pdfFmtDate(val) {
  if (!val) return '—';
  try { return new Date(val).toLocaleDateString('en-GB'); } catch { return '—'; }
}

function pdfFmtDateTime(val) {
  if (!val) return '—';
  try {
    return new Date(val).toLocaleString('en-US', {
      month: 'long', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit'
    });
  } catch { return '—'; }
}

function pdfRule(doc, y, color = PDF_COLORS.border) {
  doc.save().lineWidth(0.5).strokeColor(color)
     .moveTo(PDF_MARGIN, y).lineTo(PDF_PAGE_W - PDF_MARGIN, y).stroke().restore();
}

function pdfFilledBox(doc, x, y, w, h, fillColor, strokeColor) {
  doc.save().rect(x, y, w, h).fill(fillColor);
  if (strokeColor) doc.rect(x, y, w, h).stroke(strokeColor);
  doc.restore();
}

function pdfSectionHeading(doc, text, y) {
  doc.save().rect(PDF_MARGIN, y, 3, 14).fill(PDF_COLORS.primary).restore();
  doc.fontSize(11).font('Helvetica-Bold').fillColor(PDF_COLORS.text).text(text, PDF_MARGIN + 10, y + 1);
  return y + 22;
}

// Full-bleed brand header band drawn at the top of the first page.
// Returns the y-position where body content should resume.
function pdfHeaderBand(doc, title, subtitle) {
  doc.save().rect(0, 0, PDF_PAGE_W, 86).fill(PDF_COLORS.primary).restore();
  doc.fontSize(18).font('Helvetica-Bold').fillColor(PDF_COLORS.white)
     .text('Lumora', PDF_MARGIN, 20);
  doc.fontSize(9).font('Helvetica').fillColor('#E0E7FF')
     .text('Mental Health Support Platform', PDF_MARGIN, 43);
  doc.fontSize(13).font('Helvetica-Bold').fillColor(PDF_COLORS.white)
     .text(title, PDF_MARGIN, 61);
  if (subtitle) {
    doc.fontSize(9).font('Helvetica').fillColor('#E0E7FF')
       .text(subtitle, PDF_PAGE_W - PDF_MARGIN - 220, 63, { width: 220, align: 'right' });
  }
  return 106;
}

// Ensures `neededHeight` fits before the page's max content y; if not, starts
// a new page (with a small continuation label) and returns the y to draw at.
function pdfEnsureSpace(doc, y, neededHeight, continuationLabel) {
  if (y + neededHeight <= PDF_MAX_Y) return y;
  doc.addPage();
  let ny = 40;
  if (continuationLabel) {
    doc.fontSize(8).font('Helvetica').fillColor(PDF_COLORS.textLight)
       .text(continuationLabel, PDF_MARGIN, ny, { width: PDF_CONTENT_W, align: 'right' });
    ny += 16;
  }
  return ny;
}

function pdfFooter(doc, generatedAtLabel, note) {
  doc.fontSize(7).font('Helvetica').fillColor(PDF_COLORS.textLight)
     .text(`Generated by Lumora • ${generatedAtLabel}${note ? ` • ${note}` : ''}`, PDF_MARGIN, PDF_PAGE_H - 34, {
       align: 'center', width: PDF_CONTENT_W
     });
}

// ============================================
// 1. EXPORT JOURNAL ENTRIES AS PDF
// ============================================

router.get("/journal/:user_id/pdf", verifyToken, async (req, res) => {
  const userId = parseInt(req.params.user_id);
  const { month, year } = req.query;

  if (req.user.id !== userId) {
    return res.status(403).json({ msg: "Unauthorized" });
  }

  try {
    let query = "SELECT * FROM journals WHERE user_id = ?";
    let params = [userId];

    if (month && year) {
      query += " AND MONTH(created_at) = ? AND YEAR(created_at) = ?";
      params.push(parseInt(month), parseInt(year));
    }

    query += " ORDER BY created_at DESC";

    const [journals] = await db.promise().query(query, params);

    if (journals.length === 0) {
      return res.status(404).json({ msg: "No journal entries found for this period" });
    }

    const doc = new PDFDocument({ margin: PDF_MARGIN, size: 'A4' });
    const filename = `journal_entries_${month || 'all'}_${year || 'all'}.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    doc.pipe(res);

    const periodLabel = (month && year)
      ? `${new Date(year, month - 1).toLocaleString('default', { month: 'long' })} ${year}`
      : 'All Entries';

    let y = pdfHeaderBand(doc, 'Journal Entries', periodLabel);

    // Meta strip
    pdfFilledBox(doc, PDF_MARGIN, y, PDF_CONTENT_W, 30, PDF_COLORS.bg, PDF_COLORS.border);
    doc.fontSize(9).font('Helvetica-Bold').fillColor(PDF_COLORS.text)
       .text(`${journals.length} ${journals.length === 1 ? 'Entry' : 'Entries'}`, PDF_MARGIN + 12, y + 10);
    doc.fontSize(9).font('Helvetica').fillColor(PDF_COLORS.textMuted)
       .text(`Exported on ${pdfFmtDate(new Date())}`, PDF_PAGE_W - PDF_MARGIN - 200, y + 10, { width: 188, align: 'right' });
    y += 46;

    journals.forEach((journal, index) => {
      const dateLabel = pdfFmtDateTime(journal.created_at);
      const contentWidth = PDF_CONTENT_W - 24;
      const contentHeight = doc.heightOfString(journal.content || '', { width: contentWidth, lineGap: 3 });
      const cardHeight = 30 + contentHeight + 16;
      const fitsWithFreshPage = cardHeight <= (PDF_MAX_Y - 40);

      if (fitsWithFreshPage) {
        y = pdfEnsureSpace(doc, y, cardHeight, `Journal Entries (continued) — ${periodLabel}`);

        pdfFilledBox(doc, PDF_MARGIN, y, PDF_CONTENT_W, cardHeight, PDF_COLORS.bg, PDF_COLORS.border);
        doc.save().rect(PDF_MARGIN, y, 3, cardHeight).fill(PDF_COLORS.primary).restore();

        doc.fontSize(10).font('Helvetica-Bold').fillColor(PDF_COLORS.primary)
           .text(`Entry ${index + 1}`, PDF_MARGIN + 12, y + 10);
        doc.fontSize(8).font('Helvetica').fillColor(PDF_COLORS.textMuted)
           .text(dateLabel, PDF_PAGE_W - PDF_MARGIN - 200, y + 11, { width: 188, align: 'right' });

        pdfRule(doc, y + 26, PDF_COLORS.border);

        doc.fontSize(10).font('Helvetica').fillColor(PDF_COLORS.text)
           .text(journal.content || '', PDF_MARGIN + 12, y + 34, { width: contentWidth, lineGap: 3 });

        y += cardHeight + 10;
      } else {
        // Very long entry: fall back to plain flowing text so PDFKit can
        // paginate it safely across multiple pages without a clipped card.
        y = pdfEnsureSpace(doc, y, 40, `Journal Entries (continued) — ${periodLabel}`);

        doc.fontSize(10).font('Helvetica-Bold').fillColor(PDF_COLORS.primary)
           .text(`Entry ${index + 1}`, PDF_MARGIN, y);
        doc.fontSize(8).font('Helvetica').fillColor(PDF_COLORS.textMuted)
           .text(dateLabel, PDF_MARGIN, y + 14);
        pdfRule(doc, y + 28);
        doc.fontSize(10).font('Helvetica').fillColor(PDF_COLORS.text)
           .text(journal.content || '', PDF_MARGIN, y + 36, { width: PDF_CONTENT_W, lineGap: 3 });

        y = doc.y + 14;
      }
    });

    pdfFooter(doc, pdfFmtDateTime(new Date()));

    doc.end();
  } catch (error) {
    console.error("Export journal error:", error);
    res.status(500).json({ msg: "Failed to export journal entries" });
  }
});

// ============================================
// 2. EXPORT MOOD HISTORY AS CSV (LAST 7 DAYS)
// ============================================

router.get("/mood/:user_id/csv", verifyToken, async (req, res) => {
  const userId = parseInt(req.params.user_id);

  if (req.user.id !== userId) {
    return res.status(403).json({ msg: "Unauthorized" });
  }

  try {
    const [moods] = await db.promise().query(
      `SELECT mood, created_at FROM moods 
       WHERE user_id = ? 
       AND created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)
       ORDER BY created_at DESC`,
      [userId]
    );

    if (moods.length === 0) {
      return res.status(404).json({ msg: "No mood data found for the last 7 days" });
    }

    const moodLabels = {
      1: 'Terrible',
      2: 'Sad',
      3: 'Okay',
      4: 'Good',
      5: 'Great'
    };

    const formattedData = moods.map(m => ({
      Date: new Date(m.created_at).toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' }),
      Mood: m.mood,
      Mood_Label: moodLabels[m.mood] || 'Unknown'
    }));

    const fields = ['Date', 'Mood', 'Mood_Label'];
    const parser = new Parser({ fields });
    const csv = parser.parse(formattedData);

    const filename = `mood_history_last_7_days.csv`;
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(csv);
  } catch (error) {
    console.error("Export mood error:", error);
    res.status(500).json({ msg: "Failed to export mood data" });
  }
});

// ============================================
// 3. EXPORT SLEEP LOGS AS CSV (LAST 7 DAYS)
// ============================================

router.get("/sleep/:user_id/csv", verifyToken, async (req, res) => {
  const userId = parseInt(req.params.user_id);

  if (req.user.id !== userId) {
    return res.status(403).json({ msg: "Unauthorized" });
  }

  try {
    const [sleep] = await db.promise().query(
      `SELECT bedtime, wake_time, duration, quality, created_at FROM sleep 
       WHERE user_id = ? 
       AND created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)
       ORDER BY created_at DESC`,
      [userId]
    );

    if (sleep.length === 0) {
      return res.status(404).json({ msg: "No sleep data found for the last 7 days" });
    }

    const qualityLabels = {
      1: 'Poor',
      2: 'Fair',
      3: 'Okay',
      4: 'Good',
      5: 'Excellent'
    };

    const formattedData = sleep.map(s => ({
      Date: new Date(s.created_at).toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
      Bedtime: s.bedtime,
      Wake_Time: s.wake_time,
      Duration_hours: parseFloat(s.duration).toFixed(1),
      Quality: s.quality,
      Quality_Label: qualityLabels[s.quality] || 'Unknown'
    }));

    const fields = ['Date', 'Bedtime', 'Wake_Time', 'Duration_hours', 'Quality', 'Quality_Label'];
    const parser = new Parser({ fields });
    const csv = parser.parse(formattedData);

    const filename = `sleep_logs_last_7_days.csv`;
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(csv);
  } catch (error) {
    console.error("Export sleep error:", error);
    res.status(500).json({ msg: "Failed to export sleep data" });
  }
});

// ============================================
// 4. EXPORT ASSESSMENT RESULT AS PDF
// ============================================

router.get("/assessment/:assessment_id/pdf", verifyToken, async (req, res) => {
  const assessmentId = parseInt(req.params.assessment_id);
  const userId = req.user.id;

  try {
    const [assessments] = await db.promise().query(
      "SELECT * FROM assessments WHERE id = ? AND user_id = ?",
      [assessmentId, userId]
    );

    if (assessments.length === 0) {
      return res.status(404).json({ msg: "Assessment not found" });
    }

    const assessment = assessments[0];
    let answers = [];
    try {
      answers = JSON.parse(assessment.answers);
    } catch (e) {
      answers = [];
    }

    let questions = [];
    if (assessment.type === 'phq9') {
      questions = [
        "Little interest or pleasure in doing things",
        "Feeling down, depressed, or hopeless",
        "Trouble falling/staying asleep or sleeping too much",
        "Feeling tired or having little energy",
        "Poor appetite or overeating",
        "Feeling bad about yourself or that you're a failure",
        "Trouble concentrating on things",
        "Moving or speaking slowly, or being fidgety/restless",
        "Thoughts that you would be better off dead or hurting yourself"
      ];
    } else if (assessment.type === 'gad7') {
      questions = [
        "Feeling nervous, anxious, or on edge",
        "Not being able to stop or control worrying",
        "Worrying too much about different things",
        "Trouble relaxing",
        "Being so restless that it's hard to sit still",
        "Becoming easily annoyed or irritable",
        "Feeling afraid as if something awful might happen"
      ];
    } else if (assessment.type === 'pss') {
      questions = [
        "In the last month, how often have you been upset because of something that happened unexpectedly?",
        "In the last month, how often have you felt that you were unable to control the important things in your life?",
        "In the last month, how often have you felt nervous and 'stressed'?",
        "In the last month, how often have you felt confident about your ability to handle your personal problems?",
        "In the last month, how often have you felt that things were going your way?",
        "In the last month, how often have you found that you could not cope with all the things that you had to do?",
        "In the last month, how often have you been able to control irritations in your life?",
        "In the last month, how often have you felt that you were on top of things?",
        "In the last month, how often have you been angered because of things that happened that were outside of your control?",
        "In the last month, how often have you felt difficulties were piling up so high that you could not overcome them?"
      ];
    }

    const scoreOptions = assessment.type === 'pss'
      ? ['Never', 'Almost never', 'Sometimes', 'Fairly often', 'Very often']
      : ['Not at all', 'Several days', 'More than half the days', 'Nearly every day'];

    const maxScore = questions.length ? questions.length * (scoreOptions.length - 1) : null;

    const doc = new PDFDocument({ margin: PDF_MARGIN, size: 'A4' });
    const filename = `assessment_${assessment.type}_${assessment.id}.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    doc.pipe(res);

    const typeLabel = assessment.type ? assessment.type.toUpperCase() : 'Assessment';
    let y = pdfHeaderBand(doc, 'Assessment Results', typeLabel);

    // ── Score summary card ─────────────────────────────────────────────────
    const severityColorMap = {
      minimal: PDF_COLORS.success, low: PDF_COLORS.success,
      mild: PDF_COLORS.warning, moderate: PDF_COLORS.warning,
      moderately: PDF_COLORS.danger, severe: PDF_COLORS.danger, high: PDF_COLORS.danger,
    };
    const severityKey = (assessment.severity || '').trim().split(' ')[0].toLowerCase();
    const sevColor = severityColorMap[severityKey] || PDF_COLORS.textMuted;

    pdfFilledBox(doc, PDF_MARGIN, y, PDF_CONTENT_W, 74, PDF_COLORS.bg, PDF_COLORS.border);

    doc.fontSize(9).font('Helvetica').fillColor(PDF_COLORS.textMuted)
       .text('Total Score', PDF_MARGIN + 16, y + 14);
    doc.fontSize(26).font('Helvetica-Bold').fillColor(PDF_COLORS.primary)
       .text(`${assessment.score}${maxScore ? ` / ${maxScore}` : ''}`, PDF_MARGIN + 16, y + 30);

    doc.fontSize(9).font('Helvetica').fillColor(PDF_COLORS.textMuted)
       .text('Date Taken', PDF_MARGIN + 230, y + 14);
    doc.fontSize(12).font('Helvetica-Bold').fillColor(PDF_COLORS.text)
       .text(pdfFmtDate(assessment.taken_at), PDF_MARGIN + 230, y + 32);

    const badgeW = 130;
    pdfFilledBox(doc, PDF_PAGE_W - PDF_MARGIN - badgeW - 12, y + 22, badgeW, 28, sevColor, null);
    doc.fontSize(10).font('Helvetica-Bold').fillColor(PDF_COLORS.white)
       .text((assessment.severity || 'N/A').toUpperCase(), PDF_PAGE_W - PDF_MARGIN - badgeW - 12, y + 31, { width: badgeW, align: 'center' });

    y += 90;

    // ── Detailed results table ────────────────────────────────────────────
    y = pdfSectionHeading(doc, 'DETAILED RESULTS', y);

    if (questions.length === 0) {
      doc.fontSize(9).font('Helvetica').fillColor(PDF_COLORS.textMuted)
         .text('No detailed question data available for this assessment type.', PDF_MARGIN, y);
      y += 16;
    } else {
      const qColW = PDF_CONTENT_W - 150;
      const aColW = 150;

      pdfFilledBox(doc, PDF_MARGIN, y, PDF_CONTENT_W, 18, PDF_COLORS.primaryLight, null);
      doc.fontSize(8).font('Helvetica-Bold').fillColor(PDF_COLORS.primary)
         .text('QUESTION', PDF_MARGIN + 8, y + 5, { width: qColW });
      doc.fontSize(8).font('Helvetica-Bold').fillColor(PDF_COLORS.primary)
         .text('RESPONSE', PDF_MARGIN + 8 + qColW, y + 5, { width: aColW - 16, align: 'right' });
      y += 18;

      const answerChipColor = (val) => {
        if (typeof val !== 'number' || isNaN(val)) return PDF_COLORS.textMuted;
        const ratio = val / (scoreOptions.length - 1);
        if (ratio <= 0.25) return PDF_COLORS.success;
        if (ratio <= 0.5) return PDF_COLORS.textMuted;
        if (ratio <= 0.75) return PDF_COLORS.warning;
        return PDF_COLORS.danger;
      };

      questions.forEach((q, index) => {
        const answer = answers[index] !== undefined ? answers[index] : 'N/A';
        const answerText = scoreOptions[answer] || 'N/A';
        const qText = `${index + 1}. ${q}`;
        const qHeight = doc.heightOfString(qText, { width: qColW - 8, lineGap: 2 });
        const rowH = Math.max(22, qHeight + 12);

        y = pdfEnsureSpace(doc, y, rowH, `Detailed Results (continued) — ${typeLabel}`);

        const rowBg = index % 2 === 0 ? PDF_COLORS.white : PDF_COLORS.bg;
        pdfFilledBox(doc, PDF_MARGIN, y, PDF_CONTENT_W, rowH, rowBg, null);

        doc.fontSize(9).font('Helvetica').fillColor(PDF_COLORS.text)
           .text(qText, PDF_MARGIN + 8, y + 6, { width: qColW - 8, lineGap: 2 });

        doc.fontSize(9).font('Helvetica-Bold').fillColor(answerChipColor(answer))
           .text(answerText, PDF_MARGIN + 8 + qColW, y + 6, { width: aColW - 16, align: 'right' });

        pdfRule(doc, y + rowH);
        y += rowH;
      });
    }

    y += 16;

    // ── Interpretation note ───────────────────────────────────────────────
    const noteText = 'This assessment is a self-report screening tool and does not constitute a clinical diagnosis. Please review results together with the student and, where appropriate, a licensed mental health professional.';
    const noteHeight = doc.heightOfString(noteText, { width: PDF_CONTENT_W - 24, lineGap: 2 });
    const noteBoxHeight = noteHeight + 20;

    y = pdfEnsureSpace(doc, y, noteBoxHeight, `Assessment Results (continued) — ${typeLabel}`);
    pdfFilledBox(doc, PDF_MARGIN, y, PDF_CONTENT_W, noteBoxHeight, PDF_COLORS.primaryLight, PDF_COLORS.border);
    doc.fontSize(8).font('Helvetica').fillColor(PDF_COLORS.textMuted)
       .text(noteText, PDF_MARGIN + 12, y + 10, { width: PDF_CONTENT_W - 24, lineGap: 2 });

    pdfFooter(doc, pdfFmtDateTime(new Date()));

    doc.end();
  } catch (error) {
    console.error("Export assessment error:", error);
    res.status(500).json({ msg: "Failed to export assessment" });
  }
});

// ============================================
// 5. EXPORT APPOINTMENTS AS CSV
// ============================================

router.get("/appointments/:user_id/csv", verifyToken, async (req, res) => {
  const userId = parseInt(req.params.user_id);

  if (req.user.id !== userId) {
    return res.status(403).json({ msg: "Unauthorized" });
  }

  try {
    const [appointments] = await db.promise().query(
      `SELECT s.*, u.name as counsellor_name, u.nickname as counsellor_nickname
       FROM counselling_sessions s
       JOIN users u ON s.counsellor_id = u.id
       WHERE s.student_id = ?
       ORDER BY s.session_date DESC`,
      [userId]
    );

    if (appointments.length === 0) {
      return res.status(404).json({ msg: "No appointments found" });
    }

    const formattedData = appointments.map(a => ({
      Date: new Date(a.session_date).toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }),
      Time: new Date(a.session_date).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' }),
      Counsellor: a.counsellor_nickname || a.counsellor_name || 'Unknown',
      Duration_minutes: a.duration || 60,
      Status: a.status || 'Pending',
      Notes: a.notes || ''
    }));

    const fields = ['Date', 'Time', 'Counsellor', 'Duration_minutes', 'Status', 'Notes'];
    const parser = new Parser({ fields });
    const csv = parser.parse(formattedData);

    const filename = `appointments_export.csv`;
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(csv);
  } catch (error) {
    console.error("Export appointments error:", error);
    res.status(500).json({ msg: "Failed to export appointments" });
  }
});

module.exports = router;